import Head from "next/head";
import dynamic from "next/dynamic";
import React, { useEffect, useRef } from "react";
import styles from "@/styles/MapPage.module.css";
import KofiButton from "kofi-button";
import { Municipality } from "@/types/data";
import Loading from "@/components/Loading";
import AboutLink from "./AboutLink";
import SuggestInput from "./SuggestInput";
import Alert from "./Alert";

export interface MapPageProps {
  municipalities: Municipality[];
}

export default ({ municipalities }: MapPageProps) => {
  const [alertMessage, setAlertMessage] = React.useState("");
  const [alertVisible, setAlertVisible] = React.useState(false);

  const showAlert = (message: string) => {
    setAlertMessage(message);
    setAlertVisible(true);
    setTimeout(() => {
      setAlertVisible(false);
    }, 5000);
  };

  const inputRef = useRef<HTMLInputElement>(null);
  console.log("inputRef", inputRef);
  useEffect(() => {
    console.log("useEffect inputRef", inputRef);
  }, [inputRef.current]);

  const Map = React.useMemo(
    () =>
      dynamic(() => import("@/components/CatchmentAreaMap"), {
        loading: () => <Loading />,
        ssr: false,
      }),
    []
  );

  return (
    <>
      <Head>
        <title>Mapa pražských spádových oblastí</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <div className={styles.suggest}>
          <SuggestInput ref={inputRef} />
        </div>

        <Map
          municipalities={municipalities}
          center={[50.0874286, 14.4212811]}
          zoom={14}
          suggestInput={inputRef}
          onError={showAlert}
        />

        <div className={styles.about}>
          <div className={styles.tag}>o projektu</div>
          <ul className={styles.collapsed}>
            <AboutLink url="https://github.com/maral/text-to-map-frontend">
              Github
            </AboutLink>
            <AboutLink url="https://twitter.com/LisyMarek/status/1637777860181016581">
              Vlákno o projektu
            </AboutLink>
            <AboutLink url="praha.json">
              JSON s adresními místy ke stažení
            </AboutLink>
            <AboutLink
              url="mailto:marek.lisy.hk@gmai.com"
              prependText="Chcete mapu spádových oblastí i pro vaše město?"
            >
              Napište mi
            </AboutLink>
            <li>
              <KofiButton
                kofiID="E1E5JOMLT"
                color="#29abe0"
                title="Buy me a coffee"
              ></KofiButton>
            </li>
          </ul>
        </div>

        <Alert message={alertMessage} visible={alertVisible} />
      </main>
    </>
  );
};
