import Head from "next/head";
import dynamic from "next/dynamic";
import React, { useEffect, useRef } from "react";
import styles from "@/styles/MapPage.module.css";
import KofiButton from "kofi-button";
import { Municipality } from "@/types/data";
import Loading from "@/components/Loading";
import AboutLink from "./AboutLink";
import SuggestInput from "./SuggestInput";
import Alert from "./Alert";
import useQueryParams from "@/hooks/useQueryParams";
import { PageType } from "@/types/page";
import Link from "next/link";
import Menu from "./Menu";

export interface MapPageProps {
  municipalities: Municipality[];
  pageType: PageType;
}

export default function MapPage({ municipalities, pageType }: MapPageProps) {
  const { showSearch, showMenu, showControls } = useQueryParams(pageType);

  const [alertMessage, setAlertMessage] = React.useState("");
  const [alertVisible, setAlertVisible] = React.useState(false);

  const showAlert = (message: string) => {
    setAlertMessage(message);
    setAlertVisible(true);
    setTimeout(() => {
      setAlertVisible(false);
    }, 5000);
  };

  const inputRef = useRef<HTMLInputElement>(null);

  const Map = React.useMemo(
    () =>
      dynamic(() => import("@/components/CatchmentAreaMap"), {
        loading: () => <Loading />,
        ssr: false,
      }),
    []
  );

  return (
    <>
      <Head>
        <title>Mapa pražských spádových oblastí</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        {showSearch && (
          <div
            className={`${styles.suggest} ${
              showControls ? styles.moveRight : ""
            }`}
          >
            <SuggestInput ref={inputRef} />
          </div>
        )}

        <Map
          municipalities={municipalities}
          suggestInput={showSearch ? inputRef : undefined}
          onError={showAlert}
        />

        {showMenu && (
          <Menu moveLeft={municipalities.length > 1 && showControls} />
        )}

        <Alert message={alertMessage} visible={alertVisible} />
      </main>
    </>
  );
}
