import Loading from "@/components/Loading";
import { DataForMap } from "@/types/data";
import dynamic from "next/dynamic";
import Head from "next/head";
import React from "react";

export interface MapPageProps {
  data: DataForMap;
  showDebugInfo?: boolean;
  ordinanceText?: string;
  year?: number;
}

export default function MapPage({
  data,
  ordinanceText,
  showDebugInfo = false,
  year,
}: MapPageProps) {
  const Map = React.useMemo(
    () =>
      dynamic(() => import("@/components/Map/InnerMap"), {
        loading: () => <Loading />,
        ssr: false,
      }),
    []
  );

  return (
    <>
      <Head>
        <title>Mapa spádových oblastí pražských škol</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Map
          data={data}
          text={ordinanceText}
          showDebugInfo={showDebugInfo}
          year={year}
        />
      </main>
    </>
  );
}
